php:
    build: .
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./www:/var/www/html
    links:
        - db

db:
    image: mysql
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=myrootpass
        - MYSQL_DATABASE=mydb